import {Asset} from "./types";
function hist(base:number, seed:number){return Array.from({length:30},(_,i)=>({date:`Day ${i+1}`,value:+(base*(1+Math.sin((i+seed)/4)*.025+(i-15)*.0015)).toFixed(2)}));}
export const assets:Asset[]=[
{id:"ae_eq_aapl",slug:"apple",symbol:"AAPL",name:"Apple Inc.",assetClass:"Equities",category:"Technology",price:228.4,change:1.42,marketCap:3.42e12,currency:"USD",liquidity:99,confidence:99,description:"Illustrative public-equity profile. Production quotes should come from a licensed securities data provider.",updated:"Demo data",history:hist(228.4,1)},
{id:"ae_cr_btc",slug:"bitcoin",symbol:"BTC",name:"Bitcoin",assetClass:"Crypto",category:"Digital Currency",price:113420,change:-0.84,marketCap:2.26e12,currency:"USD",liquidity:98,confidence:99,description:"Illustrative digital-asset profile with a direct-market-price model.",updated:"Demo data",history:hist(113420,3)},
{id:"ae_co_gold",slug:"gold",symbol:"XAU",name:"Gold",assetClass:"Commodities",category:"Precious Metals",price:3678.2,change:.31,marketCap:24.6e12,currency:"USD",liquidity:97,confidence:98,description:"Illustrative spot-gold reference profile.",updated:"Demo data",history:hist(3678.2,6)},
{id:"ae_re_nyc",slug:"manhattan-residential-index",symbol:"NYC-RES",name:"Manhattan Residential Index",assetClass:"Real Estate",category:"Residential",price:1215000,change:.18,marketCap:1.1e12,currency:"USD",liquidity:48,confidence:82,location:"New York, NY",description:"Illustrative modeled residential real-estate index. Values are estimates rather than executable quotes.",updated:"Demo data",history:hist(1215000,4)},
{id:"ae_col_rolex",slug:"rolex-daytona-116500ln",symbol:"DAYTONA",name:"Rolex Daytona 116500LN",assetClass:"Collectibles",category:"Watches",price:27650,change:1.9,currency:"USD",liquidity:62,confidence:76,description:"Illustrative secondary-market watch estimate based on a hypothetical comparable-sales model.",updated:"Demo data",history:hist(27650,7)},
{id:"ae_dig_domain",slug:"premium-domain-index",symbol:"DOMAIN",name:"Premium Domain Index",assetClass:"Digital",category:"Domain Names",price:18400,change:2.6,currency:"USD",liquidity:31,confidence:61,description:"Illustrative index for scarce digital domain assets.",updated:"Demo data",history:hist(18400,2)},
{id:"ae_pm_saas",slug:"private-saas-index",symbol:"PSAAS",name:"Private SaaS Index",assetClass:"Private Markets",category:"Software",price:100,change:-.4,currency:"USD",liquidity:22,confidence:68,description:"Illustrative private-market valuation index.",updated:"Demo data",history:hist(100,8)},
{id:"ae_fx_eurusd",slug:"eur-usd",symbol:"EURUSD",name:"Euro / U.S. Dollar",assetClass:"FX",category:"Currency Pair",price:1.18,change:.12,currency:"USD",liquidity:100,confidence:99,description:"Illustrative foreign-exchange reference.",updated:"Demo data",history:hist(1.18,5)}
];
export const classes=[...new Set(assets.map(a=>a.assetClass))];
export function getAsset(slug:string){return assets.find(a=>a.slug===slug);}
